# Ejercicio opcional de Preprocesamiento 

Recibimos un dataset con información sobre la cancelación de servicios y atributos de clientes que han contratado el servicio de una empresa de telecomunicaciones. En este ejercicio deberás analizar y preparar dicho dataset para entrenar un modelo de Machine Learning que sirva para predecir la tasa de cancelación.

Cada fila del dataset representa un cliente, y cada columna es una atributo de dicho cliente. El dataset contiene la siguiente información:

- **State**: Estado donde vive el cliente.
- **Account length**: Hace cuánto tiempo el cliente contrato el servicio (en días).
- **Area code**: Código de área 
- **International plan**: ¿El cliente ha contratado un plan internacional?
- **Voice mail plan**: ¿El cliente ha contratado un plan de buzón de voz? 
- **Number vmail messages**: Número de mensajes de voz que ha recibido 
- **Total day minutes**: Minutos gastados en llamadas nacionales
- **Total day calls**: Número de llamadas nacionales realizadas 
- **Total day charge**: Cargos nacionales
- **Total intl minutes**: Minutos gastados en llamadas internacionales
- **Total intl calls**: Número de llamadas internacionales 
- **Total intl charge**: Cargos internacionales 
- **Customer service calls**: Llamadas al servicio de cliente 
- **Client type**: Tipo de cliente (frequent caller, moderate caller, infrequent caller)
- **Churn**: ¿El usuario canceló el servicio?

## Importar librerias

In [186]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

## Leer datos y realizar revisiones generales

In [187]:
df = pd.read_csv("data/churn_telco.csv", encoding='utf8')
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Client type,Churn
0,LA,117,408,No,No,0,184.50,97,31.37,8.70,4,2.35,1,moderate_caller,False
1,IN,65,415,No,No,0,129.10,137,21.95,12.70,6,3.43,4,frequent_caller,True
2,NY,161,415,No,No,0,332.90,67,56.59,5.40,9,1.46,4,infrequent_caller,True
3,SC,111,415,No,No,0,110.40,103,18.77,7.70,6,2.08,2,moderate_caller,False
4,HI,49,510,No,No,0,119.30,117,20.28,11.10,1,3.00,1,frequent_caller,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,WI,114,415,No,Yes,26,137.10,88,23.31,11.50,7,3.11,2,infrequent_caller,False
663,AL,106,408,No,Yes,29,NaN,131,NaN,8.10,3,2.19,1,frequent_caller,False
664,VT,60,415,No,No,0,193.90,118,32.96,13.20,8,3.56,3,frequent_caller,False
665,WV,159,415,No,No,0,169.80,114,28.87,11.60,4,3.13,1,frequent_caller,False
666,CT,184,510,Yes,No,0,213.80,105,36.35,5.00,10,1.35,2,moderate_caller,False

In [188]:
df.shape

(667, 15)

In [189]:
df.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   667 non-null    object
 1   Account length          667 non-null    int64
 2   Area code               667 non-null    int64
 3   International plan      667 non-null    object
 4   Voice mail plan         667 non-null    object
 5   Number vmail messages   667 non-null    int64
 6   Total day minutes       657 non-null    float64
 7   Total day calls         667 non-null    int64
 8   Total day charge        657 non-null    float64
 9   Total intl minutes      667 non-null    float64
 10  Total intl calls        667 non-null    int64
 11  Total intl charge       667 non-null    float64
 12  Customer service calls  667 non-null    int64
 13  Client type             667 non-null    object
 14  Churn                   667 non-null    bool
dtypes: bool(1), float64(4), int64(6), object(4)
memory usage: 73.7+ KB

In [190]:
df.head(5)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Client type,Churn
0,LA,117,408,No,No,0,184.50,97,31.37,8.70,4,2.35,1,moderate_caller,False
1,IN,65,415,No,No,0,129.10,137,21.95,12.70,6,3.43,4,frequent_caller,True
2,NY,161,415,No,No,0,332.90,67,56.59,5.40,9,1.46,4,infrequent_caller,True
3,SC,111,415,No,No,0,110.40,103,18.77,7.70,6,2.08,2,moderate_caller,False
4,HI,49,510,No,No,0,119.30,117,20.28,11.10,1,3.00,1,frequent_caller,False

In [191]:
df.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,667.00,667.00,667.00,657.00,667.00,657.00,667.00,667.00,667.00,667.00
mean,102.84,436.16,8.41,181.03,100.94,30.78,10.24,4.38,2.76,1.56
std,40.82,41.78,13.99,55.00,20.40,9.35,2.81,2.63,0.76,1.33
min,1.00,408.00,0.00,25.90,30.00,4.40,0.00,-1.00,0.00,0.00
25%,76.00,408.00,0.00,146.40,87.50,24.89,8.60,3.00,2.32,1.00
50%,102.00,415.00,0.00,178.40,101.00,30.33,10.50,4.00,2.84,1.00
75%,128.00,415.00,20.00,220.70,115.00,37.52,12.05,6.00,3.25,2.00
max,232.00,510.00,51.00,334.30,165.00,56.83,18.30,18.00,4.94,8.00

In [192]:
pd.set_option("display.float_format", "{:,.2f}".format)
df.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,667.00,667.00,667.00,657.00,667.00,657.00,667.00,667.00,667.00,667.00
mean,102.84,436.16,8.41,181.03,100.94,30.78,10.24,4.38,2.76,1.56
std,40.82,41.78,13.99,55.00,20.40,9.35,2.81,2.63,0.76,1.33
min,1.00,408.00,0.00,25.90,30.00,4.40,0.00,-1.00,0.00,0.00
25%,76.00,408.00,0.00,146.40,87.50,24.89,8.60,3.00,2.32,1.00
50%,102.00,415.00,0.00,178.40,101.00,30.33,10.50,4.00,2.84,1.00
75%,128.00,415.00,20.00,220.70,115.00,37.52,12.05,6.00,3.25,2.00
max,232.00,510.00,51.00,334.30,165.00,56.83,18.30,18.00,4.94,8.00

In [193]:
df.isnull().sum() #Observamos que hay nulos en las columnas 'total day minutes' y 'total day charge'.

State                      0
Account length             0
Area code                  0
International plan         0
Voice mail plan            0
Number vmail messages      0
Total day minutes         10
Total day calls            0
Total day charge          10
Total intl minutes         0
Total intl calls           0
Total intl charge          0
Customer service calls     0
Client type                0
Churn                      0
dtype: int64

In [194]:
df.head(20)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Client type,Churn
0,LA,117,408,No,No,0,184.50,97,31.37,8.70,4,2.35,1,moderate_caller,False
1,IN,65,415,No,No,0,129.10,137,21.95,12.70,6,3.43,4,frequent_caller,True
2,NY,161,415,No,No,0,332.90,67,56.59,5.40,9,1.46,4,infrequent_caller,True
3,SC,111,415,No,No,0,110.40,103,18.77,7.70,6,2.08,2,moderate_caller,False
4,HI,49,510,No,No,0,119.30,117,20.28,11.10,1,3.00,1,frequent_caller,False
5,AK,36,408,No,Yes,30,146.30,128,24.87,14.50,6,3.92,0,frequent_caller,False
6,MI,65,415,No,No,0,211.30,120,35.92,13.20,5,3.56,3,frequent_caller,False
7,ID,119,415,No,No,0,159.10,114,27.05,8.80,3,2.38,5,frequent_caller,True
8,VA,10,408,No,No,0,186.10,112,31.64,11.40,6,3.08,2,frequent_caller,False
9,WI,68,415,No,No,0,148.80,70,25.30,12.10,3,3.27,3,infrequent_caller,False
10,MN,74,510,No,Yes,33,193.70,91,32.93,14.60,3,3.94,2,infrequent_caller,False
11,HI,85,415,No,No,0,235.80,109,40.09,12.00,3,3.24,0,moderate_caller,False
12,MN,46,415,No,No,0,214.10,72,36.40,8.20,3,2.21,2,infrequent_caller,False
13,VT,128,510,No,Yes,29,179.30,104,30.48,8.60,7,2.32,0,moderate_caller,False
14,LA,155,415,No,No,0,203.40,100,34.58,8.90,4,2.40,0,moderate_caller,True
15,MT,73,415,No,No,0,160.10,110,27.22,13.00,4,3.51,0,moderate_caller,False
16,ID,77,415,No,No,0,251.80,72,42.81,9.80,7,2.65,2,infrequent_caller,True
17,MA,108,415,No,No,0,178.30,137,30.31,14.60,5,3.94,0,frequent_caller,False
18,KY,95,408,No,No,0,135.00,99,22.95,12.50,9,3.38,1,moderate_caller,False
19,MI,36,510,No,Yes,29,281.40,102,47.84,9.00,6,2.43,2,moderate_caller,False

## ¿Hay variables con valores sin sentido? Si fuese así, corrígelos

In [195]:
df[df.duplicated(keep=False)] #Vemos que no hay duplicados

Empty DataFrame
Columns: [State, Account length, Area code, International plan, Voice mail plan, Number vmail messages, Total day minutes, Total day calls, Total day charge, Total intl minutes, Total intl calls, Total intl charge, Customer service calls, Client type, Churn]
Index: []

In [196]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [197]:
df.columns

Index(['state', 'account_length', 'area_code', 'international_plan',
       'voice_mail_plan', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge', 'customer_service_calls',
       'client_type', 'churn'],
      dtype='object')

In [198]:
df.international_plan.value_counts(dropna=False)

international_plan
No     614
Yes     53
Name: count, dtype: int64

In [199]:
df.churn.value_counts(dropna= False)

churn
False    572
True      95
Name: count, dtype: int64

In [200]:
df.voice_mail_plan.value_counts(dropna= False)

voice_mail_plan
No     478
Yes    189
Name: count, dtype: int64

In [201]:
df.total_intl_calls.value_counts(dropna= False) #Observamos valores negativos.

total_intl_calls
 3     120
 4     113
 2      97
 5      93
 6      68
 7      45
 1      33
 8      25
 9      25
-1      20
 10     13
 12      3
 11      3
 15      3
 0       3
 13      1
 18      1
 14      1
Name: count, dtype: int64

In [202]:
#Cambiamos valores negativos por su valor absoluto.
df['total_intl_calls'] = df['total_intl_calls'].abs()

In [203]:
df.total_intl_calls.value_counts(dropna= False) #Comprobamos que han sido modificados.

total_intl_calls
3     120
4     113
2      97
5      93
6      68
1      53
7      45
8      25
9      25
10     13
12      3
11      3
15      3
0       3
13      1
18      1
14      1
Name: count, dtype: int64

In [204]:
df.total_intl_minutes.value_counts(dropna= False)

total_intl_minutes
11.30    17
10.90    15
10.30    14
10.10    14
10.70    13
         ..
18.00     1
15.60     1
4.60      1
14.40     1
4.20      1
Name: count, Length: 132, dtype: int64

In [205]:
df.total_day_charge.value_counts

<bound method IndexOpsMixin.value_counts of 0     31.37
1     21.95
2     56.59
3     18.77
4     20.28
       ...
662   23.31
663     NaN
664   32.96
665   28.87
666   36.35
Name: total_day_charge, Length: 667, dtype: float64>

In [206]:
df.loc[df['total_intl_calls']< 0]

Empty DataFrame
Columns: [state, account_length, area_code, international_plan, voice_mail_plan, number_vmail_messages, total_day_minutes, total_day_calls, total_day_charge, total_intl_minutes, total_intl_calls, total_intl_charge, customer_service_calls, client_type, churn]
Index: []

In [207]:
df['international_plan'] = df['international_plan'].map({'No': False, 'Yes': True}).astype(bool)

In [208]:
df['voice_mail_plan'] = df['voice_mail_plan'].map({'No': False, 'Yes': True}).astype(bool)

In [209]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   667 non-null    object
 1   account_length          667 non-null    int64
 2   area_code               667 non-null    int64
 3   international_plan      667 non-null    bool
 4   voice_mail_plan         667 non-null    bool
 5   number_vmail_messages   667 non-null    int64
 6   total_day_minutes       657 non-null    float64
 7   total_day_calls         667 non-null    int64
 8   total_day_charge        657 non-null    float64
 9   total_intl_minutes      667 non-null    float64
 10  total_intl_calls        667 non-null    int64
 11  total_intl_charge       667 non-null    float64
 12  customer_service_calls  667 non-null    int64
 13  client_type             667 non-null    object
 14  churn                   667 non-null    bool
dtypes: bool(3), float64(4), int64(6), object(2)
memory usage: 64.6+ KB

## ¿Hay variables con valores vacíos? Si fuese así, rellénalos

In [210]:
df.isnull().sum()

state                      0
account_length             0
area_code                  0
international_plan         0
voice_mail_plan            0
number_vmail_messages      0
total_day_minutes         10
total_day_calls            0
total_day_charge          10
total_intl_minutes         0
total_intl_calls           0
total_intl_charge          0
customer_service_calls     0
client_type                0
churn                      0
dtype: int64

In [211]:
#Cambiamos valores nulos de la columna 'total_day_minutes' por la mediana.
median_total_day_minutes = df['total_day_minutes'].median()
df['total_day_minutes'].fillna(median_total_day_minutes, inplace= True)

In [212]:
#Cambiamos valores nulos de la columna 'total_day_charge' por la mediana.
median_total_day_charge = df['total_day_charge'].median()
df['total_day_charge'].fillna(median_total_day_charge, inplace= True)

In [213]:
df.isnull().sum() #Comprobamos que ya no hay nulos.

state                     0
account_length            0
area_code                 0
international_plan        0
voice_mail_plan           0
number_vmail_messages     0
total_day_minutes         0
total_day_calls           0
total_day_charge          0
total_intl_minutes        0
total_intl_calls          0
total_intl_charge         0
customer_service_calls    0
client_type               0
churn                     0
dtype: int64

## ¿Qué porcentaje de los clientes en el dataset han cancelado el servicio?

In [214]:
#Calculamos el número de cancelados.
(df['churn'] == True).sum()

95

In [215]:
#Sacamos el porcentaje
(df['churn'] == True).mean()*100

14.24287856071964

## ¿Qué variables están más correladas con `Churn`?

In [216]:
df['churn'] = df['churn'].astype(int)

In [217]:
numeric_columns = df.select_dtypes(include=['int', 'float']).columns
numeric_columns

Index(['account_length', 'area_code', 'number_vmail_messages',
       'total_day_minutes', 'total_day_calls', 'total_day_charge',
       'total_intl_minutes', 'total_intl_calls', 'total_intl_charge',
       'customer_service_calls', 'churn'],
      dtype='object')

In [218]:
df[numeric_columns].corr()

,account_length,area_code,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls,churn
account_length,1.00,-0.03,-0.01,0.02,0.04,0.02,0.00,0.04,0.00,-0.03,0.01
area_code,-0.03,1.00,-0.01,0.05,-0.01,0.05,-0.04,-0.01,-0.04,0.00,0.03
number_vmail_messages,-0.01,-0.01,1.00,-0.06,-0.01,-0.06,0.03,-0.04,0.03,0.01,-0.10
total_day_minutes,0.02,0.05,-0.06,1.00,-0.03,1.00,-0.02,0.01,-0.02,0.02,0.23
total_day_calls,0.04,-0.01,-0.01,-0.03,1.00,-0.03,-0.02,-0.01,-0.02,-0.05,0.02
total_day_charge,0.02,0.05,-0.06,1.00,-0.03,1.00,-0.02,0.01,-0.02,0.02,0.23
total_intl_minutes,0.00,-0.04,0.03,-0.02,-0.02,-0.02,1.00,-0.00,1.00,-0.04,-0.00
total_intl_calls,0.04,-0.01,-0.04,0.01,-0.01,0.01,-0.00,1.00,-0.00,0.01,0.02
total_intl_charge,0.00,-0.04,0.03,-0.02,-0.02,-0.02,1.00,-0.00,1.00,-0.04,-0.00
customer_service_calls,-0.03,0.00,0.01,0.02,-0.05,0.02,-0.04,0.01,-0.04,1.00,0.23
churn,0.01,0.03,-0.10,0.23,0.02,0.23,-0.00,0.02,-0.00,0.23,1.00

In [219]:
df[numeric_columns].corr()['churn'].abs().sort_values(ascending=False)

churn                    1.00
customer_service_calls   0.23
total_day_minutes        0.23
total_day_charge         0.23
number_vmail_messages    0.10
area_code                0.03
total_day_calls          0.02
total_intl_calls         0.02
account_length           0.01
total_intl_minutes       0.00
total_intl_charge        0.00
Name: churn, dtype: float64

In [220]:
#La variable que tiene la correlación positiva más fuerte con 'churn' es el número de llamadas al servicio al cliente ('customer_service_calls') con una correlación de 0.23. Esto sugiere que a medida que aumenta el número de llamadas al servicio al cliente, la probabilidad de abandono también tiende a aumentar.

## Haz un boxplot en el que muestres la distribución de `Total day minutes` de acuerdo a si un cliente ha cancelado el servicio o no

In [221]:
fig = px.box(df, x='churn', y='total_day_minutes', points="all", title='Distribución del total de minutos por día según Churn', color='churn')
fig.update_xaxes(type='category', categoryorder='category ascending', title_text='churn', tickvals=[0, 1], ticktext=['False', 'True'])
fig.show()

In [148]:
#El boxplot con la caja más grande para True y mediana desplazada podría indicar mayor variabilidad y asimetría en los datos de churn=True en comparación con churn=False. Por otro lado, si hay menos puntos fuera de la caja para churn=True, podría indicar que, en general, los datos para churn=True son más consistentes y no hay valores extremos significativos.

## Divide el dataset en train y test, haciendo un split 90/10

In [222]:
df.columns

Index(['state', 'account_length', 'area_code', 'international_plan',
       'voice_mail_plan', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge', 'customer_service_calls',
       'client_type', 'churn'],
      dtype='object')

In [223]:
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(df, test_size=0.1, stratify=df.churn, random_state=42)

In [224]:
df_train.shape, df_test.shape

((600, 15), (67, 15))

In [225]:
df_train.churn.value_counts(normalize=True)

churn
0   0.86
1   0.14
Name: proportion, dtype: float64

In [226]:
df_test.churn.value_counts(normalize=True)

churn
0   0.85
1   0.15
Name: proportion, dtype: float64

## Crea una columna nueva en los dataset de train y test donde apliques `OrdinalEncoder` a la columna `State` (ignorar `SettingWithCopyWarning`)

In [227]:
from sklearn.preprocessing import OrdinalEncoder

df_train_final = df_train.copy()
df_test_final = df_test.copy()

encoder = OrdinalEncoder()

encoder.fit(df_train_final[['state']])

df_train_final['state_encoded'] = encoder.transform(df_train_final[['state']])
df_test_final['state_encoded'] = encoder.transform(df_test_final[['state']])

In [228]:
df_train_final.describe()

,account_length,area_code,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls,churn,state_encoded
count,600.00,600.00,600.00,600.00,600.00,600.00,600.00,600.00,600.00,600.00,600.00,600.00
mean,102.46,436.67,8.15,181.30,101.25,30.82,10.26,4.48,2.77,1.59,0.14,25.96
std,40.57,42.09,13.87,54.53,20.46,9.27,2.82,2.54,0.76,1.35,0.35,14.54
min,1.00,408.00,0.00,25.90,30.00,4.40,0.00,0.00,0.00,0.00,0.00,0.00
25%,75.00,408.00,0.00,147.07,88.00,25.00,8.60,3.00,2.32,1.00,0.00,14.75
50%,101.00,415.00,0.00,178.40,101.00,30.33,10.50,4.00,2.84,1.00,0.00,26.00
75%,127.25,415.00,19.25,218.88,115.00,37.21,12.10,6.00,3.27,2.00,0.00,39.00
max,232.00,510.00,51.00,334.30,165.00,56.83,18.30,18.00,4.94,8.00,1.00,50.00

In [229]:
df_test_final.describe()

,account_length,area_code,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls,churn,state_encoded
count,67.00,67.00,67.00,67.00,67.00,67.00,67.00,67.00,67.00,67.00,67.00,67.00
mean,106.25,431.55,10.69,178.24,98.12,30.30,10.02,4.06,2.71,1.31,0.15,27.87
std,43.12,38.90,15.00,55.44,19.79,9.43,2.69,2.37,0.73,1.16,0.36,13.48
min,7.00,408.00,0.00,44.90,48.00,7.63,2.00,1.00,0.54,0.00,0.00,4.00
25%,82.50,408.00,0.00,142.50,83.50,24.23,8.35,2.00,2.25,1.00,0.00,17.00
50%,105.00,415.00,0.00,182.30,99.00,30.99,10.10,3.00,2.73,1.00,0.00,29.00
75%,133.50,415.00,26.00,222.20,112.00,37.77,11.40,5.00,3.08,2.00,0.00,39.00
max,209.00,510.00,48.00,324.70,146.00,55.20,16.40,12.00,4.43,6.00,1.00,49.00

## Aplicar `OneHotEncoder` a la columna `Client type` (no hace falta guardar el resultado como columnas en el dataset)

In [231]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

client_type_encoded = encoder.fit_transform(df[['client_type']]) #Lo guardamos en una variable para no agregarla al df.